### ISSUE TITLE
List of open CfS.

### ISSUE THREAD

**Issue by transmokopter** [strdco/callfordataspeakers.com#2]
There will always be the situation that a speaker register post CfS announcement. Would it be possible to show a list of currently open CfS?

**Comment by dhmacher** [comment]
Excellent idea! Working on providing something like that, including a JSON or perhaps RSS API for integration purposes.

**Comment by transmokopter** [comment]
Oh, that’s awesome. If you have rest or rss or anything that can be integrated with, I’m sure services like Marcin’s datacommunity tracker would love using it.

**Comment by dhmacher** [comment]
I've published a first draft of a [REST API](https://callfordataspeakers.com/api/events) and a [human-readable list](https://callfordataspeakers.com/list).

I've published a dummy event for testing purposes.

**Comment by dhmacher** [comment]
RSS feed works, albeit with very minimal information.
