### ISSUE TITLE
Old events that are not relevant are still displayed

### ISSUE THREAD

**Issue by pituach** [strdco/callfordataspeakers.com#37]
Old events that are not relevant are still displayed. Moreover, in some cases calls To Speakers for events that have already ended are shown as active (open).

![image](https://user-images.githubusercontent.com/22382186/205385565-79740794-d317-406b-ab38-9933d20a9cde.png)

**Comment by dhmacher** [comment]
Hi,
Sorry about the late answer. This is a design choice I made, to display events 90 days back.
Also, only calls for speakers that run on Sessionize can display when the CfS closes.

**Comment by pituach** [comment]
Hi @dhmacher , this was not my main point
show the close events with a sign "CLOSED" is not the main problem and this fine of these will stay there. 

> Moreover, in some cases calls To Speakers for events that have already ended are shown as active (open

As I wrote the main issue is events which are closed and does not marked as closed. This is confusing and make us check the event since it is not marked as closed. I found a few such events as you can see in the screenshot.
