### ISSUE TITLE
Slidey date thing

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [strdco/callfordataspeakers.com#72]
Dear Mr wonderful

Is it possible to add a date slicer thingymumbob on the page to filter the events by event date?

Fanks

Mr Beard

**Comment by sqlgreen** [comment]
that's a really good idea, wish I'd thought of it.

**Comment by SQLDBAWithABeard** [comment]
<img width="867" alt="image" src="https://github.com/strdco/callfordataspeakers.com/assets/6729780/8bb4b83a-bab1-4674-a03c-22cf7295ba09">

Love it
