### ISSUE TITLE
RSS Feed is broken due to invalid characters in XML

### ISSUE THREAD

**Issue by Stralle** [strdco/callfordataspeakers.com#77]
Hi, there,

I'm using MS Power Automate to catch new events published on CFDS through parsing RSS feed. However, it started failing recently. It's due to invalid RSS feed - you can check that through RSS validator (https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Fcallfordataspeakers.com%2Ffeed). There're two issues with this feed, and first one is breaking it due to having ampersand (&) character. 

![image](https://github.com/strdco/callfordataspeakers.com/assets/24244340/1aff96e3-ccbc-4cb8-a53a-0273c876e039)

I'm not sure where would be the best place to fix this issue, I believe it might be here:
https://github.com/strdco/callfordataspeakers.com/blob/24849f0219555e4cea1d2d8115c995fb1aeccbc5/server.js#L521

I believe escaping special characters in XML (such as &, <, >, ", ') would resolve the issue. Perhaps something like:
function escapeXml(unsafeStr) {
    return unsafeStr.replace(/[<>&'"]/g, function (c) {
        switch (c) {
            case '<': return '&lt;';
            case '>': return '&gt;';
            case '&': return '&amp;';
            case '\'': return '&apos;';
            case '"': return '&quot;';
        }
    });
}

I don't have environment setup to test and validate this, so I hope someone else can pick this up... :)

**Comment by dhmacher** [comment]
Thanks! Will take a look at this asap.

**Comment by dhmacher** [comment]
I think I've fixed the issue. Thanks for the heads-up.
