### ISSUE TITLE
Add a filter for conference v user group

### ISSUE THREAD

**Issue by way0utwest** [strdco/callfordataspeakers.com#9]
There are a number of groups that need a recurring speaker for a thing like a user group. Conferences, usually need just a single call.

It would be nice to have a filter to get notified of the events that are in either or both category.

**Comment by dhmacher** [comment]
On the announcement page, I've added checkboxes for different event types:
* Conference
* Preconference session
* Usergroup
* Whether this is a paid or volunteer engagement.

The announcement email sent to speakers will reflect which category/categories an event belongs to.

I haven't created any filter for the speaker registration page, as I think more or less all speakers will be interested in most of these categories.

I can't think of a good solution (with regards to user interface or storage backend) to cater better for recurring events at this point.
